# Generated by Django 3.1.4 on 2022-02-19 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0002_auto_20220214_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='quarantaine',
        ),
        migrations.AddField(
            model_name='animal',
            name='educateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chiens', to='gestion_association.person', verbose_name='Educateur'),
        ),
        migrations.AddField(
            model_name='person',
            name='commentaire_educ',
            field=models.CharField(blank=True, max_length=500, verbose_name="Détails de l'éducateur : frais kilométriques, zone d'intervention ..."),
        ),
        migrations.AddField(
            model_name='person',
            name='is_educ',
            field=models.BooleanField(default=False, verbose_name='Educateur'),
        ),
        migrations.AddField(
            model_name='person',
            name='tarif_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tarif horaire'),
        ),
        migrations.AddField(
            model_name='preference',
            name='rehabilitation',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='NON', max_length=3, verbose_name='Réhabilitation'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='statut',
            field=models.CharField(choices=[('A_ADOPTER', "A l'adoption"), ('ADOPTABLE', 'Adoptable'), ('ADOPTION', "En cours d'adoption"), ('SOCIA', 'Sociabilisation'), ('ADOPTE', 'Adopté'), ('ADOPTE_DEFINITIF', 'Adopté définitivement'), ('REHABILITATION', 'Réhabilitation'), ('SOIN', 'En soin'), ('SEVRAGE', 'En sevrage'), ('PERDU', 'Perdu'), ('DECEDE', 'Décédé'), ('RENDU', 'Rendu à ses propriétaires'), ('RELACHE', 'Relâché'), ('PEC', 'Prendre en charge')], default='REHABILITATION', max_length=30),
        ),
    ]
