# Generated by Django 3.1.4 on 2022-03-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0003_auto_20220219_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famille',
            name='enfants',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='sociabilisation',
        ),
        migrations.AddField(
            model_name='preference',
            name='chats',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('IND', 'Indéterminé')], default='IND', max_length=3, verbose_name='Ok chats'),
        ),
        migrations.AddField(
            model_name='preference',
            name='congeneres',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('IND', 'Indéterminé')], default='IND', max_length=3, verbose_name='Ok congénères'),
        ),
        migrations.AddField(
            model_name='preference',
            name='enfants',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('IND', 'Indéterminé')], default='IND', max_length=3, verbose_name='Ok enfants'),
        ),
        migrations.AddField(
            model_name='preference',
            name='nb_heures_absence',
            field=models.IntegerField(blank=True, null=True, verbose_name=" Nombre maximum d'heures d'absence consécutives"),
        ),
        migrations.AddField(
            model_name='preference',
            name='ville',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('IND', 'Indéterminé')], default='IND', max_length=3, verbose_name='Vie en ville'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='statut',
            field=models.CharField(choices=[('A_ADOPTER', "A l'adoption"), ('ADOPTABLE', 'Adoptable'), ('ADOPTION', "En cours d'adoption"), ('ADOPTE', 'Adopté'), ('ADOPTE_DEFINITIF', 'Adopté définitivement'), ('REHABILITATION', 'Réhabilitation'), ('SOIN', 'En soin'), ('SEVRAGE', 'En sevrage'), ('PERDU', 'Perdu'), ('DECEDE', 'Décédé'), ('RENDU', 'Rendu à ses propriétaires'), ('RELACHE', 'Relâché'), ('PEC', 'Prendre en charge')], default='REHABILITATION', max_length=30),
        ),
        migrations.CreateModel(
            name='VisiteMedicale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mise_a_jour', models.DateField(auto_now=True, verbose_name='Date de mise à jour')),
                ('date', models.DateField(verbose_name='Date de la visite')),
                ('type_visite', models.CharField(choices=[('VAC_PRIMO', 'Primo vaccination'), ('VAC_RAPPEL', 'Rappel vaccination'), ('STE', 'Stérilisation'), ('IDE', 'Identification'), ('CONSULT', 'Consultation'), ('PACK_STE', 'Stérilisation, Identification, primo vaccination'), ('PACK', 'Identification, primo vaccination'), ('AUTRE', 'Autre'), ('CHIRURGIE', 'Chirurgie'), ('URGENCE', 'Urgence')], max_length=30, verbose_name='Objet de la visite')),
                ('veterinaire', models.CharField(blank=True, max_length=150)),
                ('commentaire', models.CharField(blank=True, max_length=2000)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Montant')),
                ('animaux', models.ManyToManyField(related_name='visites', to='gestion_association.Animal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
