# Generated by Django 3.1.4 on 2023-02-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0004_auto_20220320_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='contact',
            field=models.CharField(blank=True, max_length=500, verbose_name='Contact prise en charge'),
        ),
        migrations.AddField(
            model_name='famille',
            name='vehicule',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='NON', max_length=3, verbose_name='Véhiculé(e)'),
        ),
        migrations.AddField(
            model_name='parrainage',
            name='date_nouvelles',
            field=models.DateField(blank=True, null=True, verbose_name='Date des dernières nouvelles données'),
        ),
    ]
