# Generated by Django 3.1.4 on 2023-05-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0005_auto_20230210_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Robe'),
        ),
        migrations.AddField(
            model_name='animal',
            name='race',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
