# Generated by Django 3.1.4 on 2023-07-08 13:29

from django.db import migrations


def migrate_exterieur(apps, schema_editor):
    Famille = apps.get_model("gestion_association", "Famille")
    for row in Famille.objects.all():
        row.exterieur = row.preference.exterieur
        row.save(update_fields=["exterieur"])


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0008_auto_20230708_1328'),
    ]

    operations = [
        migrations.RunPython(migrate_exterieur),
    ]
