# Generated by Django 3.1.4 on 2023-07-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0009_auto_20230708_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='chats',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('IND', 'Indéterminé')], default='IND', max_length=3, verbose_name='Ok chats'),
        ),
        migrations.AddField(
            model_name='famille',
            name='congeneres',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('IND', 'Indéterminé')], default='IND', max_length=3, verbose_name='Ok congénères'),
        ),
    ]
