# Generated by Django 3.1.4 on 2023-07-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0011_auto_20230708_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famille',
            name='preference',
        ),
    ]
