# Generated by Django 3.1.4 on 2023-07-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0013_auto_20230708_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='nb_sessions',
            field=models.IntegerField(null=True, verbose_name='Nombre de séances déducation'),
        ),
        migrations.AddField(
            model_name='adoption',
            name='session_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="Montant d'une séance d'éducation"),
        ),
    ]
