# Generated by Django 3.1.4 on 2023-07-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0014_auto_20230708_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='nb_sessions',
            field=models.IntegerField(blank=True, null=True, verbose_name="Nombre de séances d'éducation"),
        ),
    ]
