# Generated by Django 3.1.4 on 2024-05-18 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0016_auto_20230923_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='educateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='educateurs', to='gestion_association.person', verbose_name='Educateur effectuant les sessions'),
        ),
        migrations.AlterField(
            model_name='visitemedicale',
            name='type_visite',
            field=models.CharField(choices=[('VAC_PRIMO', 'Primo vaccination'), ('VAC_RAPPEL', 'Rappel vaccination'), ('STE', 'Stérilisation'), ('IDE', 'Identification'), ('CONSULT', 'Consultation'), ('PACK_STE', 'Stérilisation, Identification, primo vaccination'), ('PACK', 'Identification, primo vaccination'), ('AUTRE', 'Autre'), ('CHIRURGIE', 'Chirurgie'), ('URGENCE', 'Urgence'), ('OSTEO', 'Ostéopathie')], max_length=30, verbose_name='Objet de la visite'),
        ),
    ]
