# Generated by Django 3.1.4 on 2024-05-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0017_auto_20240518_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='trainer_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='gestion_association.person', verbose_name='Educateur'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='type_training',
            field=models.CharField(choices=[('BILAN', 'Bilan comportemental'), ('PRE_SESSION', "Séance d'éducation"), ('POST_SESSION', 'Séance post adoption'), ('GARDERIE', 'Garderie canine')], max_length=30, verbose_name='Type de session'),
        ),
    ]
