# Generated by Django 3.1.4 on 2024-05-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0018_auto_20240520_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nom_pro',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom professionnel'),
        ),
    ]
