# Generated by Django 3.1.4 on 2024-07-19 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0020_auto_20240520_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Date d'achat")),
                ('content', models.CharField(blank=True, max_length=150, verbose_name='Contenu')),
                ('comment', models.CharField(blank=True, max_length=1000, verbose_name='Commentaire')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Montant')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='gestion_association.animal')),
            ],
        ),
    ]
