# Generated by Django 3.1.4 on 2024-07-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0021_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='perimetre',
            field=models.CharField(choices=[('UN', 'Périmètre 1 (Lia)'), ('DEUX', 'Périmètre 2 (Samuel)'), ('TROIS', 'Périmètre 3 (Leila)')], default='UN', max_length=30, verbose_name='Périmètre de gestion'),
        ),
        migrations.AddField(
            model_name='famille',
            name='perimetre',
            field=models.CharField(choices=[('UN', 'Périmètre 1 (Lia)'), ('DEUX', 'Périmètre 2 (Samuel)'), ('TROIS', 'Périmètre 3 (Leila)')], default='UN', max_length=30, verbose_name='Périmètre de gestion'),
        ),
    ]
