# Generated by Django 3.1.4 on 2024-10-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0022_auto_20240728_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='perimetre',
        ),
        migrations.RemoveField(
            model_name='famille',
            name='perimetre',
        ),
    ]
