# Generated by Django 3.1.4 on 2025-07-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0023_auto_20241012_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitemedicale',
            name='amount_animal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Montant par animal'),
        ),
    ]
